### ISSUE TITLE
How can I Observe subscribes with defined interval ?

### ISSUE THREAD

**Issue by ipv4sec** [plgd-dev/go-coap#219]
Now Observe subscribes Interval like is 128 second ?

How can I Observe subscribes with defined interval ?

Thinks

**Comment by jkralik** [comment]
Hi. 
Could you more explain it ? When you observe some resource, then for every change you get notification (the observed resource must support it). If you want to get content in interval then you don't need  to use observe, you can use GET command. And if you want to use combination of that, then you set ETAG option to GET. After that response of GET returns `valid code` which confirms you that you have fresh state. (ETAG must be supported by the observed resource). Otherwise it returns new content of resource with new ETAG.

**Comment by ipv4sec** [comment]
I got it,  use GET command.
