### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by JosefWN** [plgd-dev/go-coap#311]
Hi, I'm using v2.5.0, and having what looks like a memory leak in the server component of `go-coap`.

Service is receiving about 0.2 rps continuously 24/7, no load spikes in terms of requests. Memory consumption is initially ~10 MB for the entire service, but it keeps climbing. At 200 MB after two weeks now, the bulk (~95%) of which is `go-coap.ListenAndServe` and runtime overhead.

**Comment by jkralik** [comment]
Hi @JosefWN.

Do you use DTLS? If yes, do you use option `dtls.WithInactivityMonitor()`  during the creation server vi `dtls.NewServer()`? Because the session is stored infinitely when it is not set.

For analyzing memory:
Could you look at it with https://www.freecodecamp.org/news/how-i-investigated-memory-leaks-in-go-using-pprof-on-a-large-codebase-4bec4325e192 ?

Thx

**Comment by JosefWN** [comment]
I'm not using DTLS.

Yes, I arrived at my conclusion using `pprof`, I think the connections are leaking on the server side.

Try running: https://github.com/plgd-dev/go-coap/tree/master/examples/simple

To test whether the connections leak I ran the server and modified the client to repeatedly connect from new connections:

```go
func main() {
	for {
		co, err := udp.Dial("localhost:5688")
		if err != nil {
			log.Fatalf("Error dialing: %v", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), time.Second)
		_, err = co.Get(ctx, "/a")
		if err != nil {
			log.Fatalf("Error sending request: %v", err)
		}
		cancel()

		co.Close()

		time.Sleep(5 * time.Millisecond)
	}
}
```

The memory consumption on the server side is increasing indefinitely, stopped the experiment at 150 MB allocated.
