### ISSUE TITLE
preparing new v3 release

### ISSUE THREAD

**Issue by jkralik** [plgd-dev/go-coap#368]
## v3 main branch

https://github.com/plgd-dev/go-coap/tree/v3

## Features:

- [x] use only one pool.Message for tcp,udp,dtls - #325
- [x] allow get MessageID and Type from pool.Message
- [x] allow set MessageID and Type to pool.Message
- [x] https://github.com/plgd-dev/go-coap/issues/140
- [x] https://github.com/plgd-dev/go-coap/issues/312
- [x] https://github.com/plgd-dev/go-coap/issues/251
- [x] https://github.com/plgd-dev/go-coap/issues/226
- [x] update go-coap version to v3
- [x] https://github.com/plgd-dev/go-coap/issues/383
- [x] remove duplicate code as match as possible
- [x] ...

## Optional features:
- [ ] https://github.com/plgd-dev/go-coap/issues/313

## Release date
2022.10

**Comment by jkralik** [comment]
@beriberikix @tim-golioth As we prepare to release version 3, I would like to ask if you have any changes from the API side that need to be made, or if you would be able to contribute some changes, for example #313.

**Comment by tim-golioth** [comment]
I don't have anything at the moment. Only thing I had recently was #341 , but that has been approved/merged already. (Note on this one: this PR has a bug in that it looks like the actual code being returned is 4.17, not 4.29. I have a ticket in our backlog to fix this, which I'll be sure to open a PR here as well. Should be able to get it fixed this week.)

Let me take a look at #313 and see what's involved. Since this release is targeting 2022.10, it might be something I can take on.

**Comment by tim-golioth** [comment]
follow up about the 4.17/4.29 issue: this is a no-op. it was specific to our internal code. nothing related to go-coap.

**Comment by tim-golioth** [comment]
@jkralik i don't have the bandwidth to take on #313 at the moment. i am interested in the topic, so maybe i can find time in q4 to work on this. if this is urgent, maybe there is someone else who can work on it in the meantime.
